# ReGreet configuration (see https://github.com/rharish101/ReGreet)

[env]
XDG_SESSION_TYPE = "wayland"
XDG_CURRENT_DESKTOP = "Hyprland"
XDG_SESSION_DESKTOP = "Hyprland"
MOZ_ENABLE_WAYLAND = "1"
OZONE_PLATFORM = "wayland"
GDK_BACKEND = "wayland"
QT_QPA_PLATFORM = "wayland"

[GTK]
application_prefer_dark_theme = true
cursor_theme_name = "Qogir-dark"
font_name = "Inter 11"
icon_theme_name = "Numix-Circle"
theme_name = "adw-gtk3-dark"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]

[appearance]
greeting_msg = "Welcome Back!"
